name: chalet
description: Find your own place.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.0+21

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1
  firebase_core: ^2.22.0
  firebase_storage: ^11.5.1
  provider: ^6.1.1
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.2.0
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.0
  pull_to_refresh: ^2.0.0
  page_transition: ^2.1.0
  image_picker: ^1.0.4
  flutter_rating_bar: ^4.0.1
  flutter_native_image: ^0.0.6+1
  google_maps_flutter: ^2.5.0
  dio: ^5.3.3
  flutter_polyline_points: ^2.0.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  # google_place: ^0.4.7
  geoflutterfire2: ^2.3.15
  sliding_up_panel: ^2.0.0+1
  fluttertoast: ^8.2.4
  flutter_toggle_tab: ^1.4.1
  flutter_signin_button: ^2.0.0
  flutter_login_facebook: ^1.9.0
  package_info: ^2.0.2
  url_launcher: ^6.2.1
  flutter_launcher_icons: ^0.13.1
  photo_view: ^0.14.0
  timeago: ^3.6.0
  flutter_bloc: ^7.3.3
  rxdart: ^0.27.7
  equatable: ^2.0.5
  flutter_svg: ^2.0.9
  flex_color_picker: ^3.3.0
  device_info_plus: ^9.1.0
  animated_splash_screen: ^1.3.0
  custom_line_indicator_bottom_navbar: ^0.0.8
  time_machine: ^0.9.17
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/chaletIcons/
    - assets/poo/
    - assets/snake/png/
    - assets/snake/svg/
    - assets/map_marker/
    - assets/statsIcons/
    - assets/avatarIcons/
    - lib/.env

    # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Courgette
      fonts:
        - asset: assets/fonts/Courgette-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
